# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', scraper.models.FixedCharField(max_length=40, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('committer_name', models.CharField(max_length=255)),
                ('committer_email', models.CharField(max_length=255)),
                ('merge', models.BooleanField(default=False)),
                ('headline', models.CharField(default='', help_text='first line of the commit message', max_length=255)),
                ('full_message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('inserted', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.PositiveIntegerField(blank=True, null=True)),
                ('files', models.PositiveIntegerField(blank=True, null=True)),
                ('file_stats', models.TextField(blank=True, default='')),
                ('parents', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, help_text='Full url', max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'started'), (2, 'scraping error'), (30, 'deleted'), (31, 'done')], db_index=True, default=0)),
                ('log', models.CharField(default='', help_text='error message', max_length=140)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('languages', models.TextField(default='', help_text='Linguist stats')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'started'), (2, 'scraping error'), (30, 'deleted'), (31, 'done')], db_index=True, default=0)),
                ('total_repos', models.PositiveIntegerField(default=0)),
                ('processed_repos', models.PositiveIntegerField(default=0)),
                ('repos', models.ManyToManyField(to='scraper.Repo')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_commits', to='scraper.User'),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committed_commits', to='scraper.User'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Repo'),
        ),
    ]
